### ISSUE TITLE
DimensionMismatch error

### ISSUE THREAD

**Issue by Bondada20** [Mathbiomed/scLENS#1]
Hello, I am getting this error but not sure why:

@Windows-PC:/mnt/h/scLENS$ julia scLENS.jl ./../sclens_output/cd8_naive_12hrs.jld2 --out_dir ./../sclens_output/ --device cpu --out_type r --plot
parsed_args = parse_commandline() = Dict{String, Any}("arg1" => "./../sclens_output/cd8_naive_12hrs.jld2", "scaling" => "mean", "device" => "cpu", "plot" => true, "out_type" => "r", "true_label" => nothing, "out_dir" => "./../sclens_output/")
Parsed args:
  arg1  =>  "./../sclens_output/cd8_naive_12hrs.jld2"
  scaling  =>  "mean"
  device  =>  "cpu"
  plot  =>  true
  out_type  =>  "r"
  true_label  =>  nothing
  out_dir  =>  "./../sclens_output/"
cd8_naive_12hrs
preprocessing...
Inp_spec
data size: (3601, 33539), sparsity: 0.9409700501128017
**ERROR: LoadError:** DimensionMismatch: Number of columns (33536) and number of column names (33538) are not equal
Stacktrace:
  [1] DataFrame(columns::Vector{AbstractVector}, colindex::DataFrames.Index; copycols::Bool)
    @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:198
  [2] DataFrame
    @ ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:193 [inlined]
  [3] DataFrame(columns::Vector{AbstractVector}, cnames::Vector{Symbol}; makeunique::Bool, copycols::Bool)
    @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:357
  [4] DataFrame
    @ ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:357 [inlined]
  [5] DataFrame(columns::SparseMatrixCSC{Float32, Int64}, cnames::Vector{Symbol}; makeunique::Bool, copycols::Bool)
    @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:380
  [6] DataFrame
    @ ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:377 [inlined]
  [7] DataFrame
    @ ~/.julia/packages/DataFrames/58MUJ/src/dataframe/dataframe.jl:384 [inlined]
  [8] preprocess(tmp_df::DataFrame; min_tp_c::Int64, min_tp_g::Int64, max_tp_c::Float64, max_tp_g::Float64, min_genes_per_cell::Int64, max_genes_per_cell::Int64, min_cells_per_gene::Int64, mito_percent::Int64, ribo_percent::Int64)
    @ Main /mnt/h/scLENS/scLENS.jl:65
  [9] main()
    @ Main /mnt/h/scLENS/scLENS.jl:855
 [10] top-level scope
    @ /mnt/h/scLENS/scLENS.jl:946
in expression starting at /mnt/h/scLENS/scLENS.jl:946

**Comment by hkimman** [comment]
Hi, thanks for reporting this issue.

We've just released version 2.0.0 of scLENS, which includes updates that might resolve your error.
Please try the following:

1. Update to v2.0.0 and follow the updated tutorial in the README to perform your analysis interactively.
2. If the error persists, try using a file that has already gone through QC.
3. If neither works, please share the gene list you're using, and we’ll look into it.

You can find more details in the updated README.
