### ISSUE TITLE
PlotlyJS error

### ISSUE THREAD

**Issue by soo-ni42** [Mathbiomed/scLENS#2]
[julia err.txt](https://github.com/user-attachments/files/17615188/julia.err.txt)

Hello. When I run `Pkg.instantiate()` in the tutorial, I get a PlotlyJS related error like the attached file. How do I fix it? I tried to install only the PlotlyJS package, but it doesn't install. How can I solve this problem?

**Comment by hkimman** [comment]
Thank you for reporting this issue. We have identified that `PlotlyJS` can cause compatibility problems on certain operating systems and environments. To resolve this, we have replaced `PlotlyJS` with `CairoMakie` for the plotting module. Please try using the latest release.

**Comment by soo-ni42** [comment]
> Thank you for reporting this issue. We have identified that `PlotlyJS` can cause compatibility problems on certain operating systems and environments. To resolve this, we have replaced `PlotlyJS` with `CairoMakie` for the plotting module. Please try using the latest release.

Thank you for help about the issue occured. But, there was an issue about mkdir().
I ran the following code:
```
cd("C:/Julia/scLENS")
import Pkg
Pkg.activate(".")
Pkg.instantiate()
using scLENS
scLENS.tenx2jld2("C:/Julia/seq/data", "output_data.jld2")
```
And, following error occured:
```
ERROR: IOError: mkdir(""; mode=0o777): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:106 [inlined]
 [2] mkdir(path::String; mode::UInt16)
   @ Base.Filesystem .\file.jl:185
 [3] mkdir
   @ .\file.jl:177 [inlined]
 [4] tenx2jld2(p_dir::String, out_name::String, mode::String)
   @ scLENS C:\Julia\scLENS\src\scLENS.jl:897
 [5] tenx2jld2(p_dir::String, out_name::String)
   @ scLENS C:\Julia\scLENS\src\scLENS.jl:865
 [6] top-level scope
   @ c:\Julia\scLENS.jl:8
```
All three required 10X file types exist in .gz format in `"C:/Julia/seq/data"`.
What is this error and how can I fix it?

Thank you for help!

**Comment by hkimman** [comment]
Yes, the issue arose when you provided a filename without its parent folder. I have revised the code to save the output file in the current working directory without errors.
